-- Migration 0011: Phase 3 data-model additions.
--
-- 1. Customers gain a `kind` discriminator (regular vs ebay) so eBay
--    customers — who only carry a handle — live in the same list
--    behind a tab filter. `ebay_handle` is the eBay username,
--    populated only for kind='ebay'. `wants_broadcast` is the opt-in
--    flag the newsletter feature filters on.
--
-- 2. Items (which already carry a `kind` column with values 'article'
--    | 'service') gain a JSONB `attributes` map for product-specific
--    fields (tire size, profile, DOT year, …). Items also gain an
--    `online_sellable` flag and an optional `shipping_option_id` so
--    online-sellable products can advertise a preferred shipping
--    method.
--
-- 3. `shipping_options` is a CRUD table maintained from settings —
--    name, price_net, optional free-above-net threshold.
--
-- 4. `tire_storage` tracks customer-owned tires kept on the workshop
--    premises between seasons. Each entry has a human-readable
--    storage number (`L-2026-0001` style, generated by the
--    `number_ranges` mechanism, kind = 'tire_storage') and is linked
--    back to a customer + optional vehicle. Photos are stored as an
--    array of {mime, data} JSON objects so the QR-code workflow can
--    show them on the warehouse worker's phone.
--
-- 5. `workshop_hours` carries one row per weekday (0 = Sunday … 6 =
--    Saturday) with opening time, closing time, and a closed flag.
--    Drives the public-API free-slot computation.

ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "kind" varchar(20) NOT NULL DEFAULT 'regular';
--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "ebay_handle" varchar(100);
--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "wants_broadcast" boolean NOT NULL DEFAULT false;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "customers_kind_idx" ON "customers" ("kind");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "customers_wants_broadcast_idx" ON "customers" ("wants_broadcast");
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "shipping_options" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "name" varchar(150) NOT NULL,
  "description" text,
  "price_net" numeric(12, 2) NOT NULL DEFAULT '0.00',
  "free_above_net" numeric(12, 2),
  "active" boolean NOT NULL DEFAULT true,
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "shipping_options_active_idx" ON "shipping_options" ("active");
--> statement-breakpoint

ALTER TABLE "items" ADD COLUMN IF NOT EXISTS "attributes" jsonb NOT NULL DEFAULT '{}'::jsonb;
--> statement-breakpoint
ALTER TABLE "items" ADD COLUMN IF NOT EXISTS "online_sellable" boolean NOT NULL DEFAULT false;
--> statement-breakpoint
ALTER TABLE "items" ADD COLUMN IF NOT EXISTS "shipping_option_id" uuid;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "items" ADD CONSTRAINT "items_shipping_option_id_fk"
    FOREIGN KEY ("shipping_option_id")
    REFERENCES "public"."shipping_options"("id")
    ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "items_online_sellable_idx" ON "items" ("online_sellable");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "items_attributes_gin_idx" ON "items" USING GIN ("attributes");
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "tire_storage" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "storage_number" varchar(50) NOT NULL,
  "customer_id" uuid NOT NULL,
  "vehicle_id" uuid,
  "brand" varchar(80),
  "model" varchar(120),
  "size" varchar(40),
  "profile_mm" numeric(4, 1),
  "dot_year" integer,
  "season" varchar(20),
  "quantity" integer NOT NULL DEFAULT 4,
  "photos" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "notes" text,
  "stored_at" date NOT NULL DEFAULT now(),
  "retrieved_at" date,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "tire_storage_storage_number_idx" ON "tire_storage" ("storage_number");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tire_storage_customer_id_idx" ON "tire_storage" ("customer_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tire_storage_active_idx" ON "tire_storage" ("retrieved_at");
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "tire_storage" ADD CONSTRAINT "tire_storage_customer_id_fk"
    FOREIGN KEY ("customer_id")
    REFERENCES "public"."customers"("id")
    ON DELETE restrict ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "tire_storage" ADD CONSTRAINT "tire_storage_vehicle_id_fk"
    FOREIGN KEY ("vehicle_id")
    REFERENCES "public"."vehicles"("id")
    ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "workshop_hours" (
  "weekday" integer PRIMARY KEY NOT NULL,
  "opens_at" time NOT NULL DEFAULT '08:00',
  "closes_at" time NOT NULL DEFAULT '17:00',
  "closed" boolean NOT NULL DEFAULT false,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
